# DO NOT EDIT: This file is auto-generated by generate-schema/index.ts
from typing import Union
import msgspec

class StartedNotification(msgspec.Struct, tag_field="$type", tag="started"): 
    version: str
    """The version of the webview binary""" 

class IpcNotification(msgspec.Struct, tag_field="$type", tag="ipc"): 
    message: str
    """The message sent from the webview UI to the client.""" 

class ClosedNotification(msgspec.Struct, tag_field="$type", tag="closed"): 
    pass 

Notification  = Union[StartedNotification, IpcNotification, ClosedNotification] 
""" 
Messages that are sent unbidden from the webview to the client. 
""" 
class SizeWithScale(msgspec.Struct, omit_defaults=True): 
    height: float
    """The height of the window in logical pixels.""" 
    scaleFactor: float
    """The ratio between physical and logical sizes.""" 
    width: float
    """The width of the window in logical pixels.""" 

class StringResultType(msgspec.Struct, tag_field="$type", tag="string"): 
    value: str

class BooleanResultType(msgspec.Struct, tag_field="$type", tag="boolean"): 
    value: bool

class FloatResultType(msgspec.Struct, tag_field="$type", tag="float"): 
    value: float

class SizeResultType(msgspec.Struct, tag_field="$type", tag="size"): 
    value: SizeWithScale

ResultType  = Union[StringResultType, BooleanResultType, FloatResultType, SizeResultType] 
""" 
Types that can be returned from webview results. 
""" 
class AckResponse(msgspec.Struct, tag_field="$type", tag="ack"): 
    id: str

class ResultResponse(msgspec.Struct, tag_field="$type", tag="result"): 
    id: str
    result: ResultType

class ErrResponse(msgspec.Struct, tag_field="$type", tag="err"): 
    id: str
    message: str

Response  = Union[AckResponse, ResultResponse, ErrResponse] 
""" 
Responses from the webview to the client. 
""" 
class NotificationMessage(msgspec.Struct, tag_field="$type", tag="notification"): 
    data: Notification

class ResponseMessage(msgspec.Struct, tag_field="$type", tag="response"): 
    data: Response

WebViewMessage  = Union[NotificationMessage, ResponseMessage] 
""" 
Complete definition of all outbound messages from the webview to the client. 
""" 
