// DO NOT EDIT: This file is auto-generated by generate-schema/index.ts
import { z } from "npm:zod";

/**
 * Messages that are sent unbidden from the webview to the client.
 */
export type Notification =
  | {
    $type: "started";
    /** The version of the webview binary */
    version: string;
  }
  | {
    $type: "ipc";
    /** The message sent from the webview UI to the client. */
    message: string;
  }
  | {
    $type: "closed";
  };

export type SizeWithScale = {
  /** The height of the window in logical pixels. */
  height: number;
  /** The ratio between physical and logical sizes. */
  scaleFactor: number;
  /** The width of the window in logical pixels. */
  width: number;
};

/**
 * Types that can be returned from webview results.
 */
export type ResultType =
  | {
    $type: "string";

    value: string;
  }
  | {
    $type: "boolean";

    value: boolean;
  }
  | {
    $type: "float";

    value: number;
  }
  | {
    $type: "size";

    value: SizeWithScale;
  };

/**
 * Responses from the webview to the client.
 */
export type Response =
  | {
    $type: "ack";

    id: string;
  }
  | {
    $type: "result";

    id: string;

    result: ResultType;
  }
  | {
    $type: "err";

    id: string;

    message: string;
  };

/**
 * Complete definition of all outbound messages from the webview to the client.
 */
export type Message =
  | {
    $type: "notification";

    data: Notification;
  }
  | {
    $type: "response";

    data: Response;
  };

export const Notification: z.ZodType<Notification> = z.discriminatedUnion(
  "$type",
  [
    z.object({ $type: z.literal("started"), version: z.string() }),
    z.object({ $type: z.literal("ipc"), message: z.string() }),
    z.object({ $type: z.literal("closed") }),
  ],
);

export const SizeWithScale: z.ZodType<SizeWithScale> = z.object({
  height: z.number(),
  scaleFactor: z.number(),
  width: z.number(),
});

export const ResultType: z.ZodType<ResultType> = z.discriminatedUnion("$type", [
  z.object({ $type: z.literal("string"), value: z.string() }),
  z.object({ $type: z.literal("boolean"), value: z.boolean() }),
  z.object({ $type: z.literal("float"), value: z.number() }),
  z.object({ $type: z.literal("size"), value: SizeWithScale }),
]);

export const Response: z.ZodType<Response> = z.discriminatedUnion("$type", [
  z.object({ $type: z.literal("ack"), id: z.string() }),
  z.object({ $type: z.literal("result"), id: z.string(), result: ResultType }),
  z.object({ $type: z.literal("err"), id: z.string(), message: z.string() }),
]);

export const Message: z.ZodType<Message> = z.discriminatedUnion("$type", [
  z.object({ $type: z.literal("notification"), data: Notification }),
  z.object({ $type: z.literal("response"), data: Response }),
]);
